
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ERRORS = 66;
  public static final int INCREASE = 17;
  public static final int POS = 23;
  public static final int WITH = 35;
  public static final int CHAR = 3;
  public static final int ASSIGNMENT = 58;
  public static final int EQUALS = 41;
  public static final int EMPTY = 13;
  public static final int CODE_BLOCK_START = 52;
  public static final int SMALLER_THAN_EQUALS = 45;
  public static final int DOUBLE = 4;
  public static final int PRIVATE = 25;
  public static final int PARENTHESIS_SQLEFT = 57;
  public static final int INTERFACE = 19;
  public static final int INT = 6;
  public static final int ARRAY = 8;
  public static final int FOR = 14;
  public static final int GREATER_THAN = 42;
  public static final int QUOTATION_MARKS = 64;
  public static final int DEFINE = 11;
  public static final int AND = 50;
  public static final int NOT = 46;
  public static final int PARENTHESIS_SQRIGHT = 56;
  public static final int OR = 51;
  public static final int COMMA = 60;
  public static final int CALL = 9;
  public static final int NUM = 63;
  public static final int EXIT = 62;
  public static final int EOL = 59;
  public static final int SUBTRACTION = 38;
  public static final int IF = 16;
  public static final int DESTROYER_IDENTIFY = 61;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 29;
  public static final int TRUE = 49;
  public static final int SIZE = 30;
  public static final int error = 1;
  public static final int DECREASE = 10;
  public static final int VOID = 33;
  public static final int PARAMS = 22;
  public static final int CLASS_DEF = 36;
  public static final int ELSE = 12;
  public static final int FUNC = 15;
  public static final int READ = 28;
  public static final int SMALLER_THAN = 44;
  public static final int TO = 31;
  public static final int WHILE = 34;
  public static final int INSERT = 18;
  public static final int LIST = 21;
  public static final int FLOAT = 5;
  public static final int PUBLIC = 27;
  public static final int SIMPLE_QUOTATION = 65;
  public static final int THEN = 48;
  public static final int SUM = 37;
  public static final int PARENTHESIS_LEFT = 55;
  public static final int PROC = 26;
  public static final int STRING = 7;
  public static final int CODE_BLOCK_END = 53;
  public static final int FALSE = 47;
  public static final int GREATER_THAN_EQUALS = 43;
  public static final int DIVISION = 39;
  public static final int PARENTHESIS_RIGHT = 54;
  public static final int MULTIPLICATION = 40;
  public static final int VAR = 32;
  public static final int PRINT = 24;
  public static final int LENGTH = 20;
  public static final int IDENTIFIER = 67;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "CHAR",
  "DOUBLE",
  "FLOAT",
  "INT",
  "STRING",
  "ARRAY",
  "CALL",
  "DECREASE",
  "DEFINE",
  "ELSE",
  "EMPTY",
  "FOR",
  "FUNC",
  "IF",
  "INCREASE",
  "INSERT",
  "INTERFACE",
  "LENGTH",
  "LIST",
  "PARAMS",
  "POS",
  "PRINT",
  "PRIVATE",
  "PROC",
  "PUBLIC",
  "READ",
  "RETURN",
  "SIZE",
  "TO",
  "VAR",
  "VOID",
  "WHILE",
  "WITH",
  "CLASS_DEF",
  "SUM",
  "SUBTRACTION",
  "DIVISION",
  "MULTIPLICATION",
  "EQUALS",
  "GREATER_THAN",
  "GREATER_THAN_EQUALS",
  "SMALLER_THAN",
  "SMALLER_THAN_EQUALS",
  "NOT",
  "FALSE",
  "THEN",
  "TRUE",
  "AND",
  "OR",
  "CODE_BLOCK_START",
  "CODE_BLOCK_END",
  "PARENTHESIS_RIGHT",
  "PARENTHESIS_LEFT",
  "PARENTHESIS_SQRIGHT",
  "PARENTHESIS_SQLEFT",
  "ASSIGNMENT",
  "EOL",
  "COMMA",
  "DESTROYER_IDENTIFY",
  "EXIT",
  "NUM",
  "QUOTATION_MARKS",
  "SIMPLE_QUOTATION",
  "ERRORS",
  "IDENTIFIER"
  };
}

